inherit_gem:
  rubocop-github:
  - config/default.yml # generic Ruby rules and cops
  - config/rails.yml # Rails-specific rules and cops

AllCops:
  NewCops: enable
  Exclude:
    - "test/dummy/db/schema.rb"
    - "bin/*"
    - "test/dummy/db/migrate/*_engine.rb"
    - vendor/bundle/**/*
