sudo: false
language: ruby
cache: bundler
script: "bundle exec rake test"
rvm:
  - 2.2.2
  - 2.3.1
env:
  - AWS_KEY="XXX" AWS_SECRET="XXX" AWS_BUCKET="bucket" RUBYOPT="W0"
before_script:
  - bundle exec rake db:migrate
