sudo: false
language: ruby
cache: bundler
script: "bundle exec rake test"
rvm: 2.2.2
env:
  - AWS_KEY="XXX" AWS_SECRET="XXX" AWS_BUCKET="bucket"
before_script:
  - bundle exec rake db:migrate RAILS_ENV=test
