name: Build and Publish Ruby Gem on Tag Pushes
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - name: Build gem
      run: gem build fogged.gemspec
    - name: Configure RubyGems
      run: |
          mkdir -p ~/.gem
          touch ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          echo ":github: Bearer ${GITHUB_TOKEN}" > ~/.gem/credentials
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to GitHub Package Registry
      run: gem push fogged-*.gem --key github --host https://rubygems.pkg.github.com/gatemedia
