name: Build and Publish Ruby Gem on Tag Pushes
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.7
        bundler-cache: true
    - name: Build and publish gem
      uses: jstastny/publish-gem-to-github@v1.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: gatemedia
