name: Ruby

on:
  push:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.4"
          - "4.0"
    env:
      AWS_KEY: XXX
      AWS_SECRET: XXX
      AWS_BUCKET: bucket
      AWS_REGION: eu-west-1
      RUBYOPT: W0
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Database setup
      run: bundle exec rails db:create db:schema:load --trace
    - name: Run tests
      run: bundle exec rails test
    - name: Lint
      run: bundle exec rubocop
