name: Ruby

on:
  push:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_KEY: XXX
      AWS_SECRET: XXX
      AWS_BUCKET: bucket
      RUBYOPT: W0
    steps:
    - run: sudo apt-get install shared-mime-info
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
    - name: Database setup
      run: bundle exec rails db:create db:schema:load --trace
    - name: Run tests
      run: bundle exec rails test
    - name: Lint
      run: bundle exec rubocop
